// slug matches on everything that doesnt match any of the other routes

import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const SinglePostPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen justify-center ">
        <div className="w-full border-x border-slate-400  md:max-w-2xl">
          Post
        </div>
      </main>
    </>
  );
};

export default SinglePostPage;
